Se omite el job check-quality-gate

diff --git a/.github/workflows/code_analyzer.yml b/.github/workflows/code_analyzer.yml
--- a/.github/workflows/code_analyzer.yml
+++ b/.github/workflows/code_analyzer.yml
@@ -39,22 +39,22 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: ./gradlew build sonar --info
 
-  check-quality-gate:
-    name: Check SonarCloud Quality Gate Status
-    runs-on: ubuntu-latest
-    needs: sonarqube
-    steps:
-      - name: Check SonarCloud Quality Gate Status
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          PROJECT_KEY=avilajul_SOAP_API_Testing
-          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: \
-            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
-            | jq -r '.projectStatus.status')
-          
-          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
-          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
-            echo "Quality Gate failed!"
-            exit 1
-          fi
+#  check-quality-gate:
+#    name: Check SonarCloud Quality Gate Status
+#    runs-on: ubuntu-latest
+#    needs: sonarqube
+#    steps:
+#      - name: Check SonarCloud Quality Gate Status
+#        env:
+#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+#        run: |
+#          PROJECT_KEY=avilajul_SOAP_API_Testing
+#          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: \
+#            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
+#            | jq -r '.projectStatus.status')
+#
+#          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
+#          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+#            echo "Quality Gate failed!"
+#            exit 1
+#          fi
