Actualización de code_analyzer y eleiminación del job quality_gate

diff --git a/.github/workflows/code_analyzer.yml b/.github/workflows/code_analyzer.yml
--- a/.github/workflows/code_analyzer.yml
+++ b/.github/workflows/code_analyzer.yml
@@ -8,7 +8,7 @@ jobs:
     steps:
       - uses: actions/checkout@v3
         with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+          fetch-depth: 0  # Shallow clones should be disabled for better relevancy of analysis
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -39,11 +39,17 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: ./gradlew build sonar --info
 
-      - name: Trigger Quality Gate Check Workflow
+      - name: Check SonarCloud Quality Gate Status
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: |
-          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
-          -H "Accept: application/vnd.github.everest-preview+json" \
-          https://api.github.com/repos/<owner>/<repo>/dispatches \
-          -d '{"event_type":"quality_gate"}'
+          PROJECT_KEY=avilajul_SOAP_API_Testing
+          QUALITY_GATE_STATUS=$(curl -s -u $SONAR_TOKEN: \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECT_KEY" \
+            | jq -r '.projectStatus.status')
+          
+          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
+          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
